import { useEffect, useMemo, useRef, useState } from 'react';
import { demoDiff } from './data';
import type { ChangeFile, Repository, Worktree } from './domain';
import type { WorkspaceController } from './use-workspace';
import { Button, Checkbox, Icon, IconButton, Modal, Notice, SearchInput, Segmented, TextField, Textarea } from './ui';
import { Details } from './Details';

export function Diff({ file, onClose }: { file: ChangeFile; onClose: () => void }) {
  const [mode, setMode] = useState<'unified' | 'split'>('unified');
  const [copied, setCopied] = useState(false);
  const lines = demoDiff(file);
  return <section className="diff-panel"><div className="diff-heading"><div><Icon name={file.kind === 'text' ? 'code' : file.kind === 'binary' ? 'cube' : 'image'} size={17} /><strong>{file.name}</strong></div><IconButton icon="close" label="关闭 Diff" onClick={onClose} /></div><div className="diff-meta"><span>{file.path}</span><span>{file.kind === 'text' ? 'Diff · 演示片段' : `${file.kind === 'binary' ? 'Binary' : 'Image'} · ${file.size}`}</span></div>
    {file.kind === 'text' ? <><div className="diff-tools"><Segmented<'unified' | 'split'> className="small-segmented" aria-label="Diff 视图" value={mode} onValueChange={setMode} items={[{value:'unified',label:'Unified'},{value:'split',label:'Split'}]} /><IconButton icon={copied ? 'success' : 'copy'} label={copied ? '已复制 Diff' : '复制 Diff'} onClick={() => void navigator.clipboard.writeText(lines.map(l => `${l.type === 'add' ? '+' : l.type === 'remove' ? '-' : ' '}${l.text}`).join('\n')).then(() => setCopied(true))} /></div><div className={`diff-code ${mode}`}>{mode === 'unified' ? lines.map((line, i) => <div className={`diff-line ${line.type}`} key={i}><span className="line-number">{line.old ?? ''}</span><span className="line-number">{line.next ?? ''}</span><span className="diff-marker">{line.type === 'add' ? '+' : line.type === 'remove' ? '−' : ''}</span><code>{line.text}</code></div>) : <div className="split-columns">{(['before', 'after'] as const).map(side => <div key={side}><div className="split-label">{side === 'before' ? 'Before' : 'After'}</div>{lines.filter(l => side === 'before' ? l.type !== 'add' : l.type !== 'remove').map((line, i) => <div className={`diff-line ${line.type}`} key={i}><span className="line-number">{side === 'before' ? line.old : line.next}</span><code>{line.text}</code></div>)}</div>)}</div>}</div></> : <div className="binary-preview"><span className="asset-symbol"><Icon name={file.kind === 'binary' ? 'cube' : 'image'} size={42} /></span><h3>{file.kind === 'binary' ? 'Unreal 二进制资产' : '图片资产'}</h3><p>{file.kind === 'binary' ? '此文件不能显示文本 Diff。可在 Unreal Editor 中查看资产变化。' : '此演示没有原始图片内容，显示文件信息。'}</p><dl><div><dt>文件类型</dt><dd>{file.kind === 'binary' ? 'Unreal Engine asset' : 'PNG image'}</dd></div><div><dt>大小</dt><dd>{file.size}</dd></div><div><dt>状态</dt><dd>{file.tracked ? '已修改' : '新文件'}</dd></div><div><dt>存储</dt><dd>Git LFS · 演示</dd></div></dl></div>}
  </section>;
}

export function RepositoryView({ controller, repository, worktreeId, setWorktreeId, detailsTab, setDetailsTab, detailsOpen, setDetailsOpen, fileId, setFileId, globalSearch }: {
  controller: WorkspaceController; repository: Repository; worktreeId: string; setWorktreeId: (id: string) => void; detailsTab: 'graph' | 'tree'; setDetailsTab: (tab: 'graph' | 'tree') => void; detailsOpen: boolean; setDetailsOpen: (open: boolean) => void; fileId: string | undefined; setFileId: (id: string | undefined) => void; globalSearch: string;
}) {
  const worktree = repository.worktrees.find(w => w.id === worktreeId) || repository.worktrees[0];
  const [tab, setTab] = useState<'files' | 'commit'>('files');
  const [search, setSearch] = useState('');
  const [trackedOpen, setTrackedOpen] = useState(true);
  const [untrackedOpen, setUntrackedOpen] = useState(true);
  const [modal, setModal] = useState<'ai' | 'branch' | 'worktree' | null>(null);
  const [newName, setNewName] = useState('');
  const [branchWithoutWorktree, setBranchWithoutWorktree] = useState('');
  const [source, setSource] = useState<'local' | 'online'>('local');
  const busy = controller.busy[worktree.id];
  const files = worktree.files;
  const selectedFiles = files.filter(f => f.selected);
  const selectedFile = files.find(f => f.id === fileId);
  const shown = useMemo(() => files.filter(f => `${search} ${globalSearch}`.trim().toLowerCase().split(/\s+/).filter(Boolean).every(query => `${f.name} ${f.path}`.toLowerCase().includes(query))), [files, search, globalSearch]);
  const result = controller.commitResult[worktree.id];
  const previousWorktree = useRef(worktree.id);
  useEffect(() => { if (previousWorktree.current !== worktree.id) { setBranchWithoutWorktree(''); setSearch(''); setFileId(undefined); previousWorktree.current = worktree.id; } }, [worktree.id]);
  useEffect(() => {
    const onKey = (e: KeyboardEvent) => { if ((e.metaKey || e.ctrlKey) && e.key === 'Enter' && !busy && worktree.draft.summary.trim() && selectedFiles.length) { e.preventDefault(); void controller.commit(worktree.id); } };
    window.addEventListener('keydown', onKey); return () => window.removeEventListener('keydown', onKey);
  }, [worktree, busy, selectedFiles.length]);
  const chooseWorktree = (w: Worktree) => { setWorktreeId(w.id); setBranchWithoutWorktree(''); };
  const selectBranch = (branch: string) => { const match = repository.worktrees.find(w => w.branch === branch); if (match) chooseWorktree(match); else { setBranchWithoutWorktree(branch); setFileId(undefined); } };
  const addContext = () => {
    const name = newName.trim(); if (!name) return;
    if (repository.branches.includes(name) && modal === 'branch') return;
    controller.setState(s => ({ ...s, repositories: s.repositories.map(r => r.id !== repository.id ? r : modal === 'branch' ? { ...r, branches: [...r.branches, name] } : { ...r, worktrees: [...r.worktrees, { ...worktree, id: crypto.randomUUID(), label: name, branch: branchWithoutWorktree || worktree.branch, path: `~/Projects/${r.id}-${name.toLowerCase().replace(/\s+/g, '-')}`, files: [], draft: { summary: '', description: '' }, ahead: 0, behind: 0, agents: 0, presence: false, conflict: false }] }) }));
    setModal(null); setNewName('');
  };
  const requestAI = () => { if (worktree.draft.summary || worktree.draft.description) setModal('ai'); else void controller.ai(worktree.id); };
  const renderGroup = (tracked: boolean) => {
    const group = shown.filter(f => f.tracked === tracked); const total = files.filter(f => f.tracked === tracked); const open = tracked ? trackedOpen : untrackedOpen; const all = total.length > 0 && total.every(f => f.selected);
    return <section className="file-group"><div className="file-group-heading"><IconButton icon={open ? 'down' : 'right'} label={`${open ? '收起' : '展开'} ${tracked ? 'Tracked' : 'Untracked'}`} onClick={() => tracked ? setTrackedOpen(!open) : setUntrackedOpen(!open)} /><Checkbox checked={all} mixed={!all && total.some(f => f.selected)} disabled={!!busy || !total.length} label={`选择全部 ${tracked ? 'Tracked' : 'Untracked'} 文件`} onChange={() => controller.selectGroup(worktree.id, tracked)} /><strong>{tracked ? 'Tracked' : 'Untracked'}</strong><span className="count">{total.length}</span><small>{tracked ? '已跟踪的变化' : '新的文件'}</small></div>{open && <>{tracked && <div className="file-column-head"><span>Name</span><span>Change</span><span>Path</span></div>}{group.map(file => <div className={`file-row ${fileId === file.id ? 'active' : ''}`} key={file.id}><Checkbox checked={file.selected} label={`提交 ${file.name}`} disabled={!!busy} onChange={() => controller.selectFile(worktree.id, file.id)} /><button className="file-link" onClick={() => setFileId(fileId === file.id ? undefined : file.id)}><Icon name={file.kind === 'text' ? 'code' : file.kind === 'binary' ? 'cube' : 'image'} size={17} /><span>{file.name}</span></button><span className={`file-change ${file.kind === 'text' ? 'text' : ''}`}>{file.kind === 'text' ? <><span>+{file.added}</span> <span>−{file.removed}</span></> : file.kind === 'binary' ? 'Binary' : 'Image'}</span><span className="file-path">{file.path}</span><IconButton icon="more" label={`查看 ${file.name}`} onClick={() => setFileId(file.id)} /></div>)}{!group.length && <p className="group-empty">{total.length ? '没有匹配的文件' : tracked ? '没有已跟踪文件的变化' : '没有新文件'}</p>}</>}</section>;
  };
  return <div className={`repository-view ${detailsOpen ? '' : 'details-hidden'}`}>
    <aside className="repository-nav"><div className="repository-heading"><span className="repo-glyph large" style={{ color: repository.color, backgroundColor: `${repository.color}18` }}><Icon name="folder" size={23} /></span><h2>{repository.name}</h2><p>{repository.description}</p><code title={worktree.path}>{worktree.path}</code></div><Segmented<'local' | 'online'> className="source-tabs" aria-label="仓库来源" value={source} onValueChange={setSource} items={[{value:'local',label:'Local'},{value:'online',label:'Online'}]} />{source === 'online' && <p className="nav-note">当前使用本地演示数据，尚未连接在线 Presence。</p>}
    <section className="nav-section"><div className="nav-section-label"><span>BRANCHES</span><IconButton icon="plus" label="添加分支" onClick={() => { setModal('branch'); setNewName(''); }} /></div>{repository.branches.map(branch => <button key={branch} className={`branch-nav-item ${!branchWithoutWorktree && branch === worktree.branch || branch === branchWithoutWorktree ? 'active' : ''}`} onClick={() => selectBranch(branch)} title={branch}><Icon name="branch" size={15} /><span>{branch}</span>{branch === 'pc/main' || branch === 'main' ? <small>main</small> : null}</button>)}</section>
    <section className="nav-section"><div className="nav-section-label"><span>LOCAL WORKTREES</span><IconButton icon="plus" label="添加工作目录" onClick={() => { setModal('worktree'); setNewName(''); }} /></div>{repository.worktrees.map(w => <button key={w.id} className={`worktree-nav-item ${w.id === worktree.id && !branchWithoutWorktree ? 'active' : ''}`} onClick={() => chooseWorktree(w)}><div><Icon name="desktop" size={16} /><strong>{w.label}</strong>{w.agents > 0 && <span className="mini-dot teal" />}</div><small>{w.branch}</small></button>)}</section>
    <div className="context-footer"><Icon name="branch" size={15} /><span>独立工作目录<small>{files.length} 项更改 · ↑{worktree.ahead} ↓{worktree.behind}</small></span></div></aside>
    <main className="files-panel"><div className="files-tabs"><Segmented<'files' | 'commit'> className="main-tabs" aria-label="仓库视图" value={tab} onValueChange={setTab} items={[{value:'files',label:'Files',icon:<Icon name="file" size={16} />},{value:'commit',label:'Commit',icon:<Icon name="commit" size={16} />}]} /><div className="context-chip"><Icon name="branch" size={13} /><span>{worktree.branch}</span></div>{!detailsOpen && <IconButton icon="sidebar" label="展开详情栏" onClick={() => setDetailsOpen(true)} />}</div>
    {branchWithoutWorktree ? <div className="empty-state branch-empty"><Icon name="branch" size={36} /><h3>{branchWithoutWorktree}</h3><p>此分支尚未检出，没有独立的本地工作目录。</p><Button variant="secondary" className="secondary-button" onClick={() => { setModal('worktree'); setNewName(''); }}>添加演示工作目录</Button><Button variant="quiet" className="text-button" onClick={() => setBranchWithoutWorktree('')}>返回当前工作目录</Button></div> : <>{result && <Notice kind={result.kind}>{result.message}</Notice>}{busy === 'ai' && <Notice kind="info"><Icon name="spinner" size={14} className="spin" /> 正在根据 {selectedFiles.length} 个选中文件生成说明… <Button variant="quiet" className="text-button" onClick={() => controller.cancel(worktree.id)}>取消生成</Button></Notice>}
      {tab === 'files' ? <><div className="changes-heading"><div><h2>Changed files <span className="count">{files.length}</span></h2><p>工作目录中的修改，已排除忽略文件</p></div><SearchInput value={search} onChange={setSearch} placeholder="搜索文件…" /></div><div className={`changes-area ${selectedFile ? 'with-diff' : ''}`}><div className="file-list">{files.length ? <>{renderGroup(true)}{renderGroup(false)}</> : <div className="empty-state"><Icon name="success" size={38} /><h3>工作目录干净</h3><p>所有选中的更改已提交到本地演示历史。</p></div>}</div>{selectedFile && <Diff key={selectedFile.id} file={selectedFile} onClose={() => setFileId(undefined)} />}</div></> : <div className="commit-preview"><div className="changes-heading"><div><h2>Review your commit</h2><p>检查选中文件和说明，然后创建本地提交。</p></div><span className="count">{selectedFiles.length} 文件</span></div><section className="preview-message"><span className="eyebrow">SUMMARY</span><h3>{worktree.draft.summary || '尚未填写提交概要'}</h3><p>{worktree.draft.description || '可在下方补充修改原因和验证情况。'}</p></section>{selectedFiles.map(f => <button className="preview-file" key={f.id} onClick={() => { setTab('files'); setFileId(f.id); }}><Icon name={f.kind === 'binary' ? 'cube' : f.kind === 'image' ? 'image' : 'code'} size={18} /><span>{f.path}{f.name}</span><Icon name="right" size={15} /></button>)}{!selectedFiles.length && <div className="empty-state"><Icon name="file" size={28} /><h3>还没有选中文件</h3><Button variant="secondary" className="secondary-button" onClick={() => setTab('files')}>前往 Files 选择</Button></div>}</div>}
      <form className="commit-form" onSubmit={e => { e.preventDefault(); void controller.commit(worktree.id); }}><TextField className="form-row" label="Summary" id="summary" value={worktree.draft.summary} disabled={!!busy} maxLength={160} onChange={e => controller.draft(worktree.id, { summary: e.target.value })} placeholder="简短概括本次提交"  /><Textarea className="form-row" label="Description" id="description" value={worktree.draft.description} disabled={!!busy} onChange={e => controller.draft(worktree.id, { description: e.target.value })} placeholder="可选：修改原因、影响范围与验证情况"  /><div className="commit-form-footer"><span>{selectedFiles.length} files selected<span className="form-hint">待提交选择</span></span><div className="commit-actions"><Button variant="quiet" type="button" className="ai-button" disabled={!!busy || !selectedFiles.length} onClick={requestAI}><Icon name="sparkle" size={17} />AI Gen</Button><Button variant="primary" type="submit" className="primary-button" disabled={!!busy || !selectedFiles.length || !worktree.draft.summary.trim()}>{busy === 'commit' ? <Icon name="spinner" size={16} className="spin" /> : <Icon name="commit" size={16} />} {busy === 'commit' ? '提交中…' : 'Commit'}</Button></div></div></form>
    </>}</main>
    {detailsOpen && <Details key={worktree.id} worktree={worktree} tab={detailsTab} setTab={setDetailsTab} selectedFile={fileId} onFile={f => { setTab('files'); setFileId(f.id); }} onClose={() => setDetailsOpen(false)} />}
    {modal === 'ai' && <Modal title="重新生成提交说明？" onClose={() => setModal(null)}><p>你已经写了提交说明。生成结果将替换当前概要和描述，文件选择保持不变。</p><div className="modal-actions"><Button variant="secondary" className="secondary-button" onClick={() => setModal(null)}>保留我的说明</Button><Button variant="primary" className="primary-button" onClick={() => { setModal(null); void controller.ai(worktree.id); }}><Icon name="sparkle" size={16} />重新生成</Button></div></Modal>}
    {(modal === 'branch' || modal === 'worktree') && <Modal title={modal === 'branch' ? '添加演示分支' : '添加演示工作目录'} onClose={() => setModal(null)}><p>添加到当前演示仓库，不创建真实 Git 分支或磁盘目录。</p><TextField className="modal-field" label={modal === 'branch' ? '分支名称' : '工作目录名称'} value={newName} autoFocus onChange={e => setNewName(e.target.value)} placeholder={modal === 'branch' ? 'feature/controller' : 'Controller experiment'}  />{modal === 'branch' && repository.branches.includes(newName.trim()) && <Notice kind="error">该分支名称已存在。</Notice>}<div className="modal-actions"><Button variant="secondary" className="secondary-button" onClick={() => setModal(null)}>取消</Button><Button variant="primary" className="primary-button" disabled={!newName.trim() || modal === 'branch' && repository.branches.includes(newName.trim())} onClick={addContext}>添加</Button></div></Modal>}
  </div>;
}
